DROP SCHEMA `carservice` ;
CREATE DATABASE IF NOT EXISTS CarService
  DEFAULT CHARACTER SET utf8;


CREATE TABLE advertisment
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DATE DATE,
  NOTE VARCHAR(255),
  VERIFIED BIT,
  car_ID BIGINT,
  user_ID BIGINT
);
CREATE TABLE authorities
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  AUTHORITY VARCHAR(255),
  user_ID BIGINT
);
CREATE TABLE body_type
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TYPE_NAME VARCHAR(255)
);
CREATE TABLE car
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  PRICE DECIMAL(19,2),
  PRODUCE_YEAR DATE,
  TRANSMISSION INT,
  body_ID BIGINT,
  brand_ID BIGINT,
  model_ID BIGINT
);
CREATE TABLE car_brand
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  BRAND_NAME VARCHAR(255)
);
CREATE TABLE car_model
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  MODEL_NAME VARCHAR(255),
  brand_ID BIGINT
);
CREATE TABLE car_picture
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  IMAGE MEDIUMBLOB,
  PICTURE_NAME VARCHAR(255),
  car_ID BIGINT
);
CREATE TABLE phone
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  OPERATOR VARCHAR(255),
  PHONE_VALUE VARCHAR(255),
  PHONE_TYPE VARCHAR(255),
  user_ID BIGINT
);
CREATE TABLE user
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  BIRTHDAY DATE,
  EMAIL VARCHAR(255),
  ENABLED BIT,
  FIRSTNAME VARCHAR(255),
  LASTNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  REGISTRATION_DATE DATE,
  USERNAME VARCHAR(255),
  picture_ID BIGINT
);
CREATE TABLE user_picture
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  IMAGE MEDIUMBLOB,
  PICTURE_NAME VARCHAR(255)
);
ALTER TABLE advertisment ADD FOREIGN KEY ( car_ID ) REFERENCES car ( ID );
ALTER TABLE advertisment ADD FOREIGN KEY ( user_ID ) REFERENCES user ( ID );
ALTER TABLE authorities ADD FOREIGN KEY ( user_ID ) REFERENCES user ( ID );
ALTER TABLE car ADD FOREIGN KEY ( model_ID ) REFERENCES car_model ( ID );
ALTER TABLE car ADD FOREIGN KEY ( brand_ID ) REFERENCES car_brand ( ID );
ALTER TABLE car ADD FOREIGN KEY ( body_ID ) REFERENCES body_type ( ID );
ALTER TABLE car_model ADD FOREIGN KEY ( brand_ID ) REFERENCES car_brand ( ID );
ALTER TABLE car_picture ADD FOREIGN KEY ( car_ID ) REFERENCES car ( ID );
ALTER TABLE phone ADD FOREIGN KEY ( user_ID ) REFERENCES user ( ID );
ALTER TABLE user ADD FOREIGN KEY ( picture_ID ) REFERENCES user_picture ( ID );

# DO NOT USE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*INSERT INTO `carservice`.`car_brand` (BRAND_NAME)
	SELECT DISTINCT make FROM `test`.`vehiclemodelyear`;
*/

/*INSERT INTO `carservice`.`car_model` (MODEL_NAME, brand_ID)

	SELECT tv.model, cc.ID  FROM `test`.`vehiclemodelyear` as tv ,`carservice`.`car_brand` as cc
	WHERE tv.make = cc.BRAND_NAME  */
/*
SELECT
	 mark.BRAND_NAME,
	 model.MODEL_NAME
FROM `carservice`.`car_brand` as mark join `carservice`.`car_model` as model on mark.ID= model.brand_ID
*/
