CREATE DATABASE IF NOT EXISTS CarService character set utf8;

CREATE TABLE `authorities`
(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `AUTHORITY` VARCHAR(255),
  `user_ID` BIGINT,
  FOREIGN KEY ( `user_ID` ) REFERENCES `user` ( `ID` )
);
CREATE TABLE `phone`
(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `OPERATOR` VARCHAR(255),
  `PHONE_VALUE` VARCHAR(255),
  `PHONE_TYPE` VARCHAR(255),
  `user_ID` BIGINT,
  FOREIGN KEY ( `user_ID` ) REFERENCES `user` ( `ID` )
);
CREATE TABLE `user`
(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `BIRTHDAY` DATE,
  `EMAIL` VARCHAR(255),
  `ENABLED` BIT,
  `FIRSTNAME` VARCHAR(255),
  `LASTNAME` VARCHAR(255),
  `PASSWORD` VARCHAR(255),
  `REGISTRATION_DATE` DATE,
  `USERNAME` VARCHAR(255),
  `picture_ID` BIGINT,
  FOREIGN KEY ( `picture_ID` ) REFERENCES `user_picture` ( `ID` )
);
CREATE TABLE `user_picture`
(
  `ID` BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `PICTURE_NAME` VARCHAR(255),
  `user_ID` BIGINT,
  FOREIGN KEY ( `user_ID` ) REFERENCES `user` ( `ID` )
);
